### ISSUE TITLE
ScaleTime TickFormat fails on Chrome for dates before November 18th, 1883

### ISSUE THREAD

**Issue by t3db0t** [d3/d3-time-format#53] opened 2019-01-20 22:27 UTC
Replicate: In Chrome, use `scaleTime()` with `d3.axis{whichever}` and default tick settings, and set the domain to `[new Date(1883, 10), new Date(1883, 11)]`.

Expected: The automatic ticks work normally

Actual: Before Mon 19, `tickFormat` returns `:00` only

AFAICT this is due to:
"Chrome has implemented a new spec for timezone offset calculation following the merge of Make LocalTZA take 't' and 'isUTC' and drop DSTA(t) to Ecma 262. So now the time-zone conversion does not work by just backward interval of seconds, it is calculated as what local time was being observed in a specific region" [Source](https://stackoverflow.com/a/51008329/297824)

Although Chrome is currently the only browser with this issue (well, difference), it will eventually be adopted by other browsers.

I poked around through the source and I'm guessing the problem [lies in the interval measurements](https://github.com/d3/d3-scale/blob/master/src/time.js#L62), but I can't tell why. Ideas?

In the meantime I can implement my own formatter, but I hate duplicated effort :p

**Comment by mbostock** [comment] 2019-01-21 21:38
Duplicate of d3/d3-time#29.

**Closed by mbostock** 2019-01-21 21:38 UTC
