### ISSUE TITLE
d3.timeFormat is not a function - Possible unhandled promise rejection

### ISSUE THREAD

**Issue by wildman82** [d3/d3-time-format#124] opened 2024-05-14 17:56 UTC
Hello,

I'm working through a D3 tutorial and I'm getting a Possible unhandled promise rejection.

It seems like there is an issues with the "timeParse" module in this code block:

  ```
  // read data from csv and format variables
    let data = await d3.csv('https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/3_TwoNumOrdered_comma.csv')
    var parseTime = d3.timeParse("%Y-%m-%d");
  
```

The full tutorial is here:

https://paulho1973.medium.com/create-line-chart-with-d3-and-react-a0ae9a5e1f7

Grateful for any suggestions.

**Comment by Fil** [comment] 2024-05-14 18:57
I followed the tutorial to be sure, and it works as expected, showing the data in the console (with the dates properly parsed).

Are you sure you have installed d3 correctly? (`npm i d3`)

I'm going to close this since it's not a bug, please open a [discussion here](https://github.com/d3/d3/discussions) if you need more support.

**Closed as completed by Fil** 2024-05-14 18:57 UTC
