### ISSUE TITLE
Implement iso 8601 week year (%G)

### ISSUE THREAD

**Issue by eoghanmurray** [d3/d3-time-format#74] opened 2020-01-06 16:06 UTC
I came across a client bug on 1st January 2020 due to the lack of this code.

There appears to be an in-limbo pull request on this already https://github.com/d3/d3-time-format/pull/52 or https://github.com/d3/d3-time-format/pull/49 but I don't see any Issues so have created this one!

**Comment by eoghanmurray** [comment] 2020-01-06 16:07
Oh I see #42

**Comment by mbostock** [comment] 2020-01-06 17:18
Duplicate of #42 .

**Closed by mbostock** 2020-01-06 17:18 UTC
