### ISSUE TITLE
Invalid string parses but results in unexpected date

### ISSUE THREAD

**Issue by pgp44** [d3/d3-time-format#91] opened 2020-08-31 12:05 UTC
Version 3.0.0

```
import * as tf from 'd3-time-format';
console.log(tf.timeParse("%m/%d/%y")("66/8/20"));
```

==>

`2025-06-07T22:00:00.000Z
`
Would rather expect null. 

What am I missing?

Tx!

Peter

**Comment by Fil** [comment] 2020-08-31 12:35
Duplicate of https://github.com/d3/d3-time-format/issues/47

d3-time-parse does not validate the strings. You might want to test format(parse(x))===x ?

**Closed by Fil** 2020-08-31 12:35 UTC
